<a href="https://colab.research.google.com/github/camibreide/Ingenias/blob/main/Copia_de_Notebook_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [2]:
import numpy as np

In [ ]:
#1) Crear un arreglo de ceros de longitud 12
p1=np.zeros(12)
p1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#2) Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
p2=np.zeros(10)
p2[4]=10
p2

array([ 0.,  0.,  0.,  0., 10.,  0.,  0.,  0.,  0.,  0.])

In [ ]:
#3) Crear un arreglo que tenga los números del 10 al 49
p3 = np.array(range(10, 50))
p3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [8]:
#4) Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
p4=np.array([[0,1,2],[3,4,5],[6,7,8]])
p4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
#5) Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
p5=np.random.rand(100)
#da valores de 0 a 1
#para elegir el rango de los valores np.random.randint(): Generates an array of random integers within a specified range.
media=np.mean(p5)
varianza=np.var(p5)
print(p5, media, varianza)

[0.31161979 0.38650434 0.09863519 0.66505713 0.04371009 0.04346441
 0.00157533 0.47488545 0.92856308 0.55363984 0.74754799 0.77310829
 0.66115328 0.40852199 0.39834184 0.44179453 0.15229965 0.04420188
 0.69026732 0.44364128 0.43136055 0.47878429 0.92564998 0.12642352
 0.43437587 0.14243736 0.52362975 0.06198158 0.82997495 0.95131152
 0.90569416 0.0546082  0.1763406  0.30734332 0.47018742 0.9577853
 0.58843857 0.14943198 0.74064295 0.56204747 0.41490522 0.83359711
 0.5143636  0.47194773 0.473874   0.01124687 0.45759053 0.47398459
 0.65250679 0.50809455 0.92945063 0.22192863 0.78307287 0.25649302
 0.74727024 0.0813986  0.33535288 0.991639   0.88445023 0.25303306
 0.36291746 0.86289701 0.77283478 0.06052443 0.78382663 0.87166587
 0.9623765  0.79873046 0.33151436 0.4866754  0.37433232 0.04382547
 0.77549841 0.1650897  0.32592659 0.4201107  0.67088143 0.24811117
 0.51431745 0.36466912 0.5071326  0.46248721 0.2888419  0.24888133
 0.39963927 0.60321115 0.90218579 0.58658917 0.81859627 0.79132

In [13]:
#6) Calcular la media de un arreglo usando np.sum
media6=np.sum(p5)/np.size(p5)
media6
#utilizo el array del punto 5 para poder verificar facilmente los resultados

0.5033041142816687

In [19]:
#7) Calcular la varianza de un arreglo usando np.sum y np.mean
var7=(np.sum((p5-np.mean(p5))*(p5-np.mean(p5))))/(np.size(p5)-1)
var7

0.07744566029703112

In [20]:
#Crear un array de números aleatorios usando np.random.randn.
p8=np.random.randn(6)
p8

array([ 0.72008556, -0.8158801 ,  0.68417374, -1.12663225, -0.86385276,
        0.27957249])